[build]
  command = "python --version && pip install -r requirements.txt"
  functions = "functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200